name: Basic Firmware Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install west
      run: |
        pip install west
    
    - name: Get SDK
      run: |
        west init -m https://github.com/nrfconnect/sdk-nrf --mr v2.7.0
        west update
    
    - name: Clean and prepare build directory
      run: |
        rm -rf build/
        mkdir -p build/
    
    - name: Build
      run: |
        west build -b nrf52840dk_nrf52840 .
    
    - name: Save firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          build/zephyr/zephyr.hex
          build/zephyr/merged.hex