name: Basic Firmware Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake gcc-arm-none-eabi binutils-arm-none-eabi
        pip install west
        pip install -r zephyr/scripts/requirements.txt || pip install pyelftools

    - name: Cache SDK
      id: cache-sdk
      uses: actions/cache@v4
      with:
        path: |
          zephyr
          nrf
          ncs
          modules
          bootloader
          tools
        key: ${{ runner.os }}-ncs-v2.7.0
    
    - name: Get SDK
      if: steps.cache-sdk.outputs.cache-hit != 'true'
      run: |
        west init -m https://github.com/nrfconnect/sdk-nrf --mr v2.7.0
        west update

    - name: Cache Zephyr SDK
      id: cache-zephyr-sdk
      uses: actions/cache@v4
      with:
        path: zephyr-sdk-0.16.3
        key: ${{ runner.os }}-zephyr-sdk-0.16.3
    
    - name: Install Zephyr SDK
      if: steps.cache-zephyr-sdk.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/zephyr-sdk-0.16.3_linux-x86_64.tar.xz
        tar xf zephyr-sdk-0.16.3_linux-x86_64.tar.xz
        cd zephyr-sdk-0.16.3
        ./setup.sh -c -t arm-zephyr-eabi

    - name: Set Zephyr SDK Environment
      run: |
        echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
        echo "ZEPHYR_SDK_INSTALL_DIR=$GITHUB_WORKSPACE/zephyr-sdk-0.16.3" >> $GITHUB_ENV

    - name: Initialize west workspace
      run: |
        cd $GITHUB_WORKSPACE  # Ensure you're in the correct directory
        if [ -f "west.yml" ]; then
          echo "West workspace detected."
        else
          echo "West workspace not found! Initializing..."
          west init -m https://github.com/nrfconnect/sdk-nrf --mr v2.7.0
          west update
        fi
        west zephyr-export
    
    - name: Clean and prepare build directory
      run: |
        rm -rf build/
        mkdir -p build/
    
    - name: Build
      run: |
        west build -p auto -b nrf52840dk_nrf52840 . -- -DCONFIG_BOOTLOADER_MCUBOOT=y
        west sign -t imgtool --tool-path bootloader/mcuboot/scripts/imgtool.py --build-dir build
    
    - name: List build files
      run: |
        ls -la build/zephyr/
    
    - name: Save firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          build/zephyr/*.hex
          build/zephyr/*.bin
          build/zephyr/zephyr.*